# Generated by Django 4.1.4 on 2023-01-28 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('dec', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=4, default=500, max_digits=6)),
                ('pic', models.FileField(default='sad_seller.png', upload_to='product_images')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
    ]
