# Generated by Django 4.1.4 on 2023-01-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='emai',
            new_name='email',
        ),
    ]
