# Generated by Django 4.1.4 on 2023-01-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_rename_emai_buyer_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
