# Generated by Django 4.1.4 on 2023-01-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyer', '0004_delete_buyer_delete_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('addres', models.TextField(max_length=250)),
                ('mobile', models.CharField(max_length=15)),
                ('pic', models.FileField(default='sad.webp', upload_to='buyer_profile')),
            ],
        ),
    ]
